---
- hosts: <host>
  become: yes
  task:
    - name: update packages
      apt:
        name: '*'
        state: present
    - name: install coreutils
      apt:
        name: 'coreutils'
        state: present
    - name: download node_export
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
        dest: /opt/node_export/
    - name: tar file
      unarchive:
        src: /opt/node_export/node_exporter-1.2.2.linux-amd64.tar.gz
        dest: /opt/node_export/
    - name: run node_export
      shell: 
        
      
